[profile.default]
# The source directory
src = 'src'
# The artifact directory
out = 'out'
# A list of paths to look for libraries in
libs = ['lib']
# Whether or not to enable `vm.ffi`
ffi = true
# Enables or disables via-ir
via-ir = false
# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 15_000
# Improves verification
bytecode_hash = "none"
# EVM version
evm_version = "london"
# Version to compile with
solc_version = "0.8.19"
# Contracts to track with --gas-report
gas_reports = ["FraxGovernorAlpha", "FraxGovernorOmega", "VeFxsVotingDelegation", "FraxGuard"]

[fuzz]
# Amount of runs per fuzz test
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 1000 # This gets overriden by prettier afterwards
tab_width = 4
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"